---
title: "Estadísticas Descriptivas"
author: "Antonio Huerta Montellano"
date: "8/1/2023"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(sandwich) 
library(stargazer)
library(ggplot2)

knitr::opts_chunk$set(collapse = TRUE, fig.pos = "H")
```

```{r directorio, include = FALSE}
getwd()
```


## Estadísticas Descriptivas

Importemos las bases de datos con las que se van a trabajar

```{r bases_de_datos, message = FALSE}
setwd("/home/usuario/Documentos/Github/Proyectos/MLB_HN")
# Auxiliares
csv <- ".csv"
# Directorios
hitters_path <- "ETL_Data/Agent/First_Year_Contract/Period_t/Free_Agent/Hitters/panel_hitters"
pitchers_path <-"ETL_Data/Agent/First_Year_Contract/Period_t/Free_Agent/Pitchers/panel_pitchers"
# Bases de datos:
panel_hitter <- read_csv(paste(hitters_path, csv, sep = ""))
panel_pitcher <- read_csv(paste(pitchers_path, csv, sep = ""))
```

Observemos una breve descripción de las columnas que contiene cada base de datos

```{r informacion_general}
# Hitters
###############################################################################
############################ Hitters ##########################################
###############################################################################
str(panel_hitter)
###############################################################################
############################ Pitchers #########################################
###############################################################################
str(panel_pitcher)
```

Creemos un vector que contenga el nombre de las variables de interés

```{r aux_visualizacion}
hitter_statistics <- list('At-bats', 'Bateos_promedio', 'Dobles', 
                     'Home-runs', 'Porcentaje_On-base-plus-slugging',
                     'Porcentaje_juegos', 'Porcentaje_juegos_iniciados',
                     'Porcentaje_on-base', 'Porcentaje_slugging', 'Runs-batted-in',
                     'Triples', 'WAR')
pitcher_statistics <- list('Bateos_en_contra', 'Carreras_en_contra', 'Carreras_ganadas',
                      'Comando', 'Control', 'Dominio', 'ERA', 'Inning_pitched',
                      'Porcentaje_juegos', 'Juegos_iniciados', 'Losses', 'Saves',
                      'Strike-outs', 'WAR', 'WHIP', 'Walks', 'Wins')
```

```{r}
hitter_statistics[1]
```



```{r}
delta <- 1.7188 # Ver CT
w.sd <- sd(panel_hitter$Porcentaje_slugging)
w.iqr.adj <- IQR(panel_hitter$Porcentaje_slugging)/1.349
w.N <- nrow(panel_hitter)
constante <- 1.3643
ajuste <- min(w.sd,w.iqr.adj)
h <- constante*delta*ajuste*w.N^(-0.2) # ancho de banda
# Change line colors by groups
ggplot(panel_hitter, aes(x = Porcentaje_slugging,
                         color = Agente_libre,
                         fill = Agente_libre)) +
geom_histogram(aes(y = ..density..) ,
               bins = 10,
               position = "identity",
               alpha = 0.7) +
geom_density(kernel = "epanechnikov",
             alpha = 0.1,
             bw = h/2,
             linetype = "solid") +
#geom_vline(data=mu, aes(xintercept=grp.mean, color=sex),
#           linetype="dashed")+
scale_color_manual(values = c("#999999",
                            "#E69F00", 
                            "#56B4E9"))+
scale_fill_manual(values = c("#999999",
                           "#E69F00",
                           "#56B4E9"))+
labs(title="Weight histogram plot",
     x = "Weight(kg)",
     y = "Density")+
theme_classic()
```

```{r}
delta <- 1.7188 # Ver CT
w.sd <- sd(panel_hitter$WAR)
w.iqr.adj <- IQR(panel_hitter$WAR)/1.349
w.N <- nrow(panel_hitter)
constante <- 1.3643
ajuste <- min(w.sd,w.iqr.adj)
h <- constante*delta*ajuste*w.N^(-0.2) # ancho de banda
# Change line colors by groups
ggplot(panel_hitter[panel_hitter$Agente_libre == 'Si',],
       aes(x = WAR)) +
geom_histogram(aes(y = ..density..) ,
               bins = 20,
               position = "identity",
               alpha = 0.7) +
geom_density(kernel = "epanechnikov",
             alpha = 0.1,
             bw = h/2,
             linetype = "solid") +
#geom_vline(data=mu, aes(xintercept=grp.mean, color=sex),
#           linetype="dashed")+
scale_color_manual(values = c("#999999",
                            "#E69F00", 
                            "#56B4E9"))+
scale_fill_manual(values = c("#999999",
                           "#E69F00",
                           "#56B4E9"))+
labs(title="Weight histogram plot",
     x = "Weight(kg)",
     y = "Density")+
theme_classic()
```
```{r}
v <- ggplot(data=panel_hitter , aes(x=WAR))
v + geom_histogram(binwidth=10 , aes(fill=Agente_libre) , 
                   color="Black")

# Facetas:
v + geom_histogram(binwidth=10 , aes(fill=Agente_libre) , 
                   color="Black") + 
  facet_grid(Agente_libre~.)

v + geom_histogram(binwidth=10 , aes(fill=Agente_libre) , 
                   color="Black") + 
  facet_grid(Agente_libre~. , scale="free")
```

