---
title: "Dynamic Model - Identification"
author: "Antonio Huerta Montellano"
date: "\today"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(comment = NA)
options(warn = FALSE) # ignore warnings
```

```{r libraries, include=FALSE}
library(lmtest) # for robust standard errors
library(dplyr) # for group_by function
library(ggplot2) # for better plots
library(dplyr) # for data managment
library(clubSandwich) # Grouped errors
library(sandwich) # MOre error options
library(tidyr) # Datframes manipulation
library(stargazer) # For output formats
library(lubridate)
library(plm)
```

```{r import_panel, include = FALSE, warning = FALSE}
setwd("C:/Users/metal/Documents/Github/MLB_hardball_negotations/")
hitters_panel <- read.csv('ETL_Data/Panel/Cumulative/Dynamic_model/panel_hitters_t_1.csv')
fielders_panel <- read.csv('ETL_Data/Panel/Cumulative/Dynamic_model/panel_fielders_t_1.csv')
```

```{r etl_panel, include = FALSE, warning = FALSE}
# Convert categorical column to numerical
# Position;
hitters_panel$position_num_t <- as.numeric(factor(hitters_panel$Posicion_t))
fielders_panel$position_num_t <- as.numeric(factor(fielders_panel$Posicion_t))
# Team:
hitters_panel$team_num_t <- as.numeric(factor(hitters_panel$Acronimo_t))
fielders_panel$team_num_t <- as.numeric(factor(fielders_panel$Acronimo_t))

# add a column of 1s to the panel data
#hitters_panel <- cbind(hitters_panel, fa = rep(1, nrow(hitters_panel)))
#fielders_panel <- cbind(fielders_panel, fa = rep(1, nrow(fielders_panel)))

hitters_panel %>% count(Posicion_t, sort = TRUE)
fielders_panel %>% count(Posicion_t, sort = TRUE)

# split the data frame by category
split_hitter <- split(hitters_panel, f = hitters_panel$Posicion_t)
split_fielder <- split(fielders_panel, f = fielders_panel$Posicion_t)

# Whole panel:
# Offensive:
h_category_1 <- split_hitter[["SP"]]
h_category_2 <- split_hitter[["RP"]]
h_category_3 <- split_hitter[["RP/CL"]]
h_category_4 <- split_hitter[["C"]]
h_category_5 <- split_hitter[["1B"]]
h_category_6 <- split_hitter[["2B"]]
h_category_7 <- split_hitter[["3B"]]
h_category_8 <- split_hitter[["SS"]]
h_category_9 <- split_hitter[["RF"]]
h_category_10 <- split_hitter[["CF"]]
h_category_11 <- split_hitter[["LF"]]
d_hitter_data <- split_hitter[["DH"]]

# Defensive:
starting_data <- split_fielder[["SP"]]
b_category_2 <- split_fielder[["RP"]]
b_category_3 <- split_fielder[["RP/CL"]]
shorts_data <- split_fielder[["SS"]]

# All panels:
# Hitters:
# Concatenate the two categories
hitter_data <- rbind(h_category_1, h_category_2, h_category_3, h_category_4,
                     h_category_5, h_category_6, h_category_7, h_category_8,
                     h_category_9, h_category_10, h_category_11)
hitter_data <- unique(hitter_data)

# Fielders:
# Concatenate the two categories
relief_pitcher_data <- rbind(b_category_2, b_category_3)
relief_pitcher_data <- unique(relief_pitcher_data)

# LIsta de variables acumuladas y anualmente promediadas_
stat_hitter <- list("X_At_bats", "X_At_bats_2",
                    "X_Bateos", "X_Bateos_2",
                    "X_Bateos_promedio", "X_Bateos_promedio_2", 
                    "X_Dobles", "X_Dobles_2",
                    "X_Home_runs", "X_Home_runs_2",
                    "X_Ingresos_equipo", "X_Ingresos_equipo_2",
                    "X_Juegos_iniciados", "X_Juegos_iniciados_2",
                    "X_Porcentaje_On_base_plus_slugging", "X_Porcentaje_On_base_plus_slugging_2",
                    "X_Porcentaje_on_base", "X_Porcentaje_on_base_2",
                    "X_Porcentaje_slugging", "X_Porcentaje_slugging_2",
                    "X_Runs_batted_in", "X_Runs_batted_in_2",
                    "X_Triples", "X_Triples_2",
                    "X_WAR", "X_WAR_2")

# Add suffix "_t" to each name
stat_hitter_t <- paste0(stat_hitter, "_t")
stat_hitter_t_1 <- paste0(stat_hitter, "_t_1")

# LIsta de variables acumuladas y anualmente promediadas_
stat_fielder <- list('X_Bateos_2', 'X_Bateos',
                     'X_Carreras_2', 'X_Carreras_ganadas_2',
                     'X_Carreras_ganadas', 'X_Carreras',
                     'X_Comando_2', 'X_Comando',
                     'X_Control_2', 'X_Control',
                     'X_Dominio_2', 'X_Dominio',
                     'X_ERA_2', 'X_ERA',
                     "X_Ingresos_equipo", "X_Ingresos_equipo_2",
                     'X_Inning_pitched_2', 'X_Inning_pitched',
                     'X_Losses_2', 'X_Losses',
                     'X_Saves_2', 'X_Saves',
                     'X_Strike_outs_2', 'X_Strike_outs',
                     'X_WAR_2', 'X_WAR',
                     'X_WHIP_2', 'X_WHIP',
                     'X_Walks_2', 'X_Walks',
                     'X_Wins_2', 'X_Wins')

# Add suffix "_t" to each name
stat_fielder_t <- paste0(stat_fielder, "_t")
stat_fielder_t_1 <- paste0(stat_fielder, "_t_1")

# Control variables:
vars_ms  <- 'Y ~ I(Edad_t^2) + I(Anios_de_contrato_t^2) + I(team_num_t^2) + X_Ingresos_equipo_t + X_Ingresos_equipo_t_1 - 1'
vars_fe  <- 'Y ~ I(Edad_t^2) + I(Anios_de_contrato_t^2) + I(team_num_t^2) + X_Ingresos_equipo_t + X_Ingresos_equipo_t_1 - 1'

hitter_stats_1 = c("Edad$_{t}^2$", "Años contrato$_{t}^2$", "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                   "$X_{AB_{t}}$","$X_{AB_{t-1}}$","$X_{AB^{2}_{t}}$","$X_{AB^{2}_{t-1}}$",
                   "$X_{H_{t}}$","$X_{H_{t-1}}$","$X_{H^{2}_{t}}$","$X_{H^{2}_{t-1}}$",
                   "$X_{BA_{t}}$","$X_{BA_{t-1}}$", "$X_{BA^{2}_{t}}$","$X_{BA^{2}_{t-1}}$",
                   "Agente$_{t}$")
hitter_stats_2 = c("Edad$_{t}^2$", "Años contrato$_{t}^2$", "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                   "$X_{D_{t}}$","$X_{D_{t-1}}$","$X_{D^{2}_{t}}$","$X_{D^{2}_{t-1}}$",
                   "$X_{HR_{t}}$","$X_{HR_{t-1}}$","$X_{HR^{2}_{t}}$","$X_{HR^{2}_{t-1}}$",
                   "$X_{GS_{t}}$","$X_{GS_{t-1}}$", "$X_{GS^{2}_{t}}$","$X_{GS^{2}_{t-1}}$",
                   "Agente$_{t}$")
hitter_stats_3 = c("Edad$_{t}^2$" , "Años contrato$_{t}^2$", "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                   "$X_{OPS_{t}}$","$X_{OPS_{t-1}}$","$X_{OPS^{2}_{t}}$","$X_{OPS^{2}_{t-1}}$",
                   "$X_{OBP_{t}}$","$X_{OBP_{t-1}}$","$X_{OBP^{2}_{t}}$","$X_{OBP^{2}_{t-1}}$",
                   "$X_{SLG_{t}}$","$X_{SLG_{t-1}}$", "$X_{SLG^{2}_{t}}$","$X_{SLG^{2}_{t-1}}$",
                   "Agente$_{t}$")
hitter_stats_4 = c("Edad$_{t}^2$" , "Años contrato$_{t}^2$", "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                   "$X_{RBI_{t}}$","$X_{RBI_{t-1}}$","$X_{RBI^{2}_{t}}$","$X_{RBI^{2}_{t-1}}$",
                   "$X_{T_{t}}$","$X_{T_{t-1}}$","$X_{T^{2}_{t}}$","$X_{T^{2}_{t-1}}$",
                   "$X_{WAR_{t}}$","$X_{WAR_{t-1}}$", "$X_{WAR^{2}_{t}}$","$X_{WAR^{2}_{t-1}}$",
                   "Agente$_{t}$")
hitter_stats <- list(hitter_stats_1,
                     hitter_stats_2,
                     hitter_stats_3,
                     hitter_stats_4)

# Cycles for loop
hitter_rep <- 4
# Stats to show
hitter_stat_num <- 6

hitter_stats_long <- list(c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{AB_{t}}$","$X_{AB_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{AB^{2}_{t}}$","$X_{AB^{2}_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{H_{t}}$","$X_{H_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{H^{2}_{t}}$","$X_{H^{2}_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{BA_{t}}$","$X_{BA_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{BA^{2}_{t}}$","$X_{BA^{2}_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{D_{t}}$","$X_{D_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{D^{2}_{t}}$","$X_{D^{2}_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{HR_{t}}$","$X_{HR_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{HR^{2}_{t}}$","$X_{HR^{2}_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{GS_{t}}$","$X_{GS_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{GS^{2}_{t}}$","$X_{GS^{2}_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{OPS_{t}}$","$X_{OPS_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{OPS^{2}_{t}}$","$X_{OPS^{2}_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{OBP_{t}}$","$X_{OBP_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{OBP^{2}_{t}}$","$X_{OBP^{2}_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{SLG_{t}}$","$X_{SLG_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{SLG^{2}_{t}}$","$X_{SLG^{2}_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{RBI_{t}}$","$X_{RBI_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{RBI^{2}_{t}}$","$X_{RBI^{2}_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{T_{t}}$","$X_{T_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{T^{2}_{t}}$","$X_{T^{2}_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{WAR_{t}}$","$X_{WAR_{t-1}}$",
                            "Agente$_{t}$"),
                          c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                            "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                            "$X_{WAR^{2}_{t}}$","$X_{WAR^{2}_{t-1}}$",
                            "Agente$_{t}$")
                          )

fielder_stats_1 = c("Edad$_{t}^2$" , "Años contrato$_{t}^2$", "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                    "$X_{H^{2}_{t}}$","$X_{H^{2}_{t-1}}$","$X_{H_{t}}$","$X_{H_{t-1}}$",
                    "$X_{R^{2}_{t}}$","$X_{R^{2}_{t-1}}$","$X_{ER^{2}_{t}}$","$X_{ER^{2}_{t-1}}$",
                    "$X_{ER_{t}}$","$X_{ER_{t-1}}$", "$X_{R_{t}}$","$X_{R_{t-1}}$",
                    "Agente$_{t}$")
fielder_stats_2 = c("Edad$_{t}^2$" , "Años contrato$_{t}^2$", "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                    "$X_{Comando^{2}_{t}}$","$X_{Comando^{2}_{t-1}}$","$X_{Comando_{t}}$","$X_{Comando_{t-1}}$",
                    "$X_{Control^{2}_{t}}$","$X_{Control^{2}_{t-1}}$","$Control_{H_{t}}$","$X_{Control_{t-1}}$",
                    "$X_{Dominio^{2}_{t}}$","$X_{Dominio^{2}_{t-1}}$","$X_{Dominio_{t}}$","$X_{Dominio_{t-1}}$",
                    "Agente$_{t}$")
fielder_stats_3 = c("Edad$_{t}^2$" , "Años contrato$_{t}^2$", "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                    "$X_{ERA^{2}_{t}}$","$X_{ERA^{2}_{t-1}}$","$X_{ERA_{t}}$","$X_{ERA_{t-1}}$",
                    "$X_{IP^{2}_{t}}$","$X_{IP^{2}_{t-1}}$","$X_{IP_{t}}$","$X_{IP_{t-1}}$",
                    "$X_{L^{2}_{t}}$","$X_{L^{2}_{t-1}}$", "$X_{L_{t}}$","$X_{L_{t-1}}$",
                    "Agente$_{t}$")
fielder_stats_4 = c("$Edad_{t}$" , "Años contrato$_{t}^2$", "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                    "$X_{S^{2}_{t}}$","$X_{S^{2}_{t-1}}$","$X_{S_{t}}$","$X_{S_{t-1}}$",
                    "$X_{SO^{2}_{t}}$","$X_{SO^{2}_{t-1}}$","$X_{SO_{t}}$","$X_{SO_{t-1}}$",
                    "$X_{WAR^{2}_{t}}$","$X_{WAR^{2}_{t-1}}$","$X_{WAR_{t}}$","$X_{WAR_{t-1}}$",
                    "Agente$_{t}$")
fielder_stats_5 = c("Edad$_{t}^2$" , "Años contrato$_{t}^2$", "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                    "$X_{WHIP^{2}_{t}}$","$X_{WHIP^{2}_{t-1}}$","$X_{WHIP_{t}}$","$X_{WHIP_{t-1}}$",
                    "$X_{BB^{2}_{t}}$","$X_{BB^{2}_{t-1}}$","$X_{BB_{t}}$","$X_{BB_{t-1}}$",
                    "$X_{W^{2}_{t}}$","$X_{W^{2}_{t-1}}$","$X_{W_{t}}$","$X_{W_{t-1}}$",
                    "Agente$_{t}$")
fielder_stats <- list(fielder_stats_1,
                      fielder_stats_2,
                      fielder_stats_3,
                      fielder_stats_4,
                      fielder_stats_5)
# Cycles for loop
fielder_rep <- 5
# Stats to show
fielder_stat_num <- 6

fielder_stats_long <- list(c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{H^{2}_{t}}$","$X_{H^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{H_{t}}$","$X_{H_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{R^{2}_{t}}$","$X_{R^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{ER^{2}_{t}}$","$X_{ER^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{ER_{t}}$","$X_{ER_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{R_{t}}$","$X_{R_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{Comando^{2}_{t}}$","$X_{Comando^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{Comando_{t}}$","$X_{Comando_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{Control^{2}_{t}}$","$X_{Control^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{Control_{t}}$","$X_{Control_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{Dominio^{2}_{t}}$","$X_{Dominio^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{Dominio_{t}}$","$X_{Dominio_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{ERA^{2}_{t}}$","$X_{ERA^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{ERA_{t}}$","$X_{ERA_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{IP^{2}_{t}}$","$X_{IP^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{IP_{t}}$","$X_{IP_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{L^{2}_{t}}$","$X_{L^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{DL_{t}}$","$X_{L_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{S^{2}_{t}}$","$X_{S^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{S_{t}}$","$X_{S_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{SO^{2}_{t}}$","$X_{SO^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{SO_{t}}$","$X_{SO_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{WAR^{2}_{t}}$","$X_{WAR^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{WAR_{t}}$","$X_{WAR_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{WHIP^{2}_{t}}$","$X_{WHIP^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{WHIP_{t}}$","$X_{WHIP_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{BB^{2}_{t}}$","$X_{BB^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{BB_{t}}$","$X_{BB_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{W^{2}_{t}}$","$X_{W^{2}_{t-1}}$",
                              "Agente$_{t}$"),
                            c("Edad$_{t}^2$","Años contrato$_{t}^2$",
                              "Equipo$_{t}^2$","X_Ingresos_equipo$_{t}$","X_Ingresos_equipo$_{t-1}$",
                              "$X_{W_{t}}$","$X_{W_{t-1}}$",
                              "Agente$_{t}$")
                            )

```

```{r}
names(hitters_panel)
```

```{r hitter_stimation_simple_pooling, echo=FALSE, eval=TRUE}
# Create a model to store the results
hitter_simple_pooling <- list()

# To store the results
hitter_results_simple_pooling_1 <- list()
hitter_results_simple_pooling_2 <- list()
hitter_results_simple_pooling_3 <- list()
hitter_results_simple_pooling_4 <- list()
hitter_results_simple_pooling <- list(result_1 = hitter_results_simple_pooling_1,
                                      result_2 = hitter_results_simple_pooling_2,
                                      result_3 = hitter_results_simple_pooling_3,
                                      result_4 = hitter_results_simple_pooling_4)

# Loop over the variables in var_hitter_list
for (j in 1:hitter_rep){
  
  for (i in 1:hitter_stat_num){
    # Run linear regression with grouped errors by country and robust errors
    base_vars_h  <- paste(vars_ms, stat_hitter_t[[i + hitter_stat_num*(j - 1)]],
                        sep = '+')
    formula <- paste(base_vars_h,
                     stat_hitter_t_1[[i + hitter_stat_num*(j - 1)]],
                     sep = " + ")
    
    hitter_simple_pooling[[i + hitter_stat_num*(j - 1)]] <- plm(formula, data = hitter_data,
                                                  model = "pooling",
                                                  index = c("id", "Anio_ref"))
        
    hitter_results_simple_pooling[[j]][[i]] <- coeftest(hitter_simple_pooling[[i + hitter_stat_num*(j - 1)]],
                                                        vcov = vcovHC(hitter_simple_pooling[[i + hitter_stat_num*(j - 1)]],
                                                                      type = "HC1",
                                                                      cluster = "group"))
  }
  
  # Print the third block of results
  stargazer(hitter_results_simple_pooling[[j]],
          no.space = TRUE,
          type = "latex",
          title = "Bateadores: Modelo Pooling",
          covariate.labels = hitter_stats[[j]])
}
```

### Starting pitcher

```{r starting_stimation_pooling, echo=FALSE, eval=TRUE}
# Create a model to store the results
fielder_simple_pooling <- list()

# To store the results
fielder_results_simple_pooling_1 <- list()
fielder_results_simple_pooling_2 <- list()
fielder_results_simple_pooling_3 <- list()
fielder_results_simple_pooling_4 <- list()
fielder_results_simple_pooling_5 <- list()
fielder_results_simple_pooling <- list(result_1 = fielder_results_simple_pooling_1,
                                       result_2 = fielder_results_simple_pooling_2,
                                       result_3 = fielder_results_simple_pooling_3,
                                       result_4 = fielder_results_simple_pooling_4,
                                       result_5 = fielder_results_simple_pooling_5)

# Loop over the variables in var_hitter_list
for (j in 1:fielder_rep){
  
  for (i in 1:fielder_stat_num){
    # Run linear regression with grouped errors by country and robust errors
    base_vars_h  <- paste(vars_ms, stat_fielder_t[[i + fielder_stat_num*(j - 1)]],
                        sep = '+')
    formula <- paste(base_vars_h,
                     stat_fielder_t_1[[i + fielder_stat_num*(j - 1)]],
                     sep = " + ")
    
    fielder_simple_pooling[[i + fielder_stat_num*(j - 1)]] <- plm(formula, data = starting_data,
                                                  model = "pooling",
                                                  index = c("id", "Anio_ref"))
        
    fielder_results_simple_pooling[[j]][[i]] <- coeftest(fielder_simple_pooling[[i + fielder_stat_num*(j - 1)]],
                                                         vcov = vcovHC(fielder_simple_pooling[[i + fielder_stat_num*(j - 1)]],
                                                                       type = "HC1",
                                                                       cluster = "group"))
  }
  
  # Print the third block of results
  stargazer(fielder_results_simple_pooling[[j]],
          no.space = TRUE,
          type = "latex",
          title = "Lanzadores Iniciales: Modelo Pooling",
          covariate.labels = fielder_stats[[j]])
}
```

## Efectos fijos

### Bateadores

Se obtendrán las estimaciones de las variables referentes a estadísticas deportivas sin controles

```{r hitter_stimation_simple_within, echo=FALSE, eval=TRUE}
# Create a model to store the results
hitter_simple_within <- list()

# To store the results
hitter_results_simple_within_1 <- list()
hitter_results_simple_within_2 <- list()
hitter_results_simple_within_3 <- list()
hitter_results_simple_within_4 <- list()
hitter_results_simple_within <- list(result_1 = hitter_results_simple_within_1,
                                      result_2 = hitter_results_simple_within_2,
                                      result_3 = hitter_results_simple_within_3,
                                      result_4 = hitter_results_simple_within_4)

# Loop over the variables in var_hitter_list
for (j in 1:hitter_rep){
  
  for (i in 1:hitter_stat_num){
    # Run linear regression with grouped errors by country and robust errors
    base_vars_h  <- paste(vars_fe, stat_hitter_t[[i + hitter_stat_num*(j - 1)]],
                        sep = '+')
    formula <- paste(base_vars_h,
                     stat_hitter_t_1[[i + hitter_stat_num*(j - 1)]],
                     sep = " + ")
    
    hitter_simple_within[[i + hitter_stat_num*(j - 1)]] <- plm(formula, data = hitter_data,
                                                  model = "within",
                                                  index = c("id", "Anio_ref"))
        
    hitter_results_simple_within[[j]][[i]] <- coeftest(hitter_simple_within[[i + hitter_stat_num*(j - 1)]],
                                                        vcov = vcovHC(hitter_simple_within[[i + hitter_stat_num*(j - 1)]],
                                                                      type = "HC1",
                                                                      cluster = "group"))
  }
  
  # Print the third block of results
  stargazer(hitter_results_simple_within[[j]],
          no.space = TRUE,
          type = "latex",
          title = "Bateadores: Estimador Within",
          covariate.labels = hitter_stats[[j]])
}
```

### Starting pitcher

```{r starting_stimation_within, echo=FALSE, eval=TRUE}
# Create a model to store the results
fielder_simple_within <- list()

# To store the results
fielder_results_simple_within_1 <- list()
fielder_results_simple_within_2 <- list()
fielder_results_simple_within_3 <- list()
fielder_results_simple_within_4 <- list()
fielder_results_simple_within_5 <- list()
fielder_results_simple_within <- list(result_1 = fielder_results_simple_within_1,
                                       result_2 = fielder_results_simple_within_2,
                                       result_3 = fielder_results_simple_within_3,
                                       result_4 = fielder_results_simple_within_4,
                                       result_5 = fielder_results_simple_within_5)

# Loop over the variables in var_hitter_list
for (j in 1:fielder_rep){
  
  for (i in 1:fielder_stat_num){
    # Run linear regression with grouped errors by country and robust errors
    base_vars_h  <- paste(vars_fe, stat_fielder_t[[i + fielder_stat_num*(j - 1)]],
                        sep = '+')
    formula <- paste(base_vars_h,
                     stat_fielder_t_1[[i + fielder_stat_num*(j - 1)]],
                     sep = " + ")
    
    fielder_simple_within[[i + hitter_stat_num*(j - 1)]] <- plm(formula, data = starting_data,
                                                  model = "within",
                                                  index = c("id", "Anio_ref"))
        
    fielder_results_simple_within[[j]][[i]] <- coeftest(fielder_simple_within[[i + fielder_stat_num*(j - 1)]],
                                                         vcov = vcovHC(fielder_simple_within[[i + fielder_stat_num*(j - 1)]],
                                                                       type = "HC1",
                                                                       cluster = "group"))
  }
  
  # Print the third block of results
  stargazer(fielder_results_simple_within[[j]],
          no.space = TRUE,
          type = "latex",
          title = "Lanzadores Iniciales: Estimador Within",
          covariate.labels = fielder_stats[[j]])
}
```

## Efectos aleatorios

### Bateadores

Se obtendrán las estimaciones de las variables referentes a estadísticas deportivas sin controles

```{r hitter_stimation_simple_random, echo=FALSE, eval=TRUE}
# Create a model to store the results
hitter_simple_random <- list()

# To store the results
hitter_results_simple_random_1 <- list()
hitter_results_simple_random_2 <- list()
hitter_results_simple_random_3 <- list()
hitter_results_simple_random_4 <- list()
hitter_results_simple_random <- list(result_1 = hitter_results_simple_random_1,
                                      result_2 = hitter_results_simple_random_2,
                                      result_3 = hitter_results_simple_random_3,
                                      result_4 = hitter_results_simple_random_4)

# Loop over the variables in var_hitter_list
for (j in 1:hitter_rep){
  
  for (i in 1:hitter_stat_num){
    # Run linear regression with grouped errors by country and robust errors
    base_vars_h  <- paste(vars_ms, stat_hitter_t[[i + hitter_stat_num*(j - 1)]],
                        sep = '+')
    formula <- paste(base_vars_h,
                     stat_hitter_t_1[[i + hitter_stat_num*(j - 1)]],
                     sep = " + ")
    
    hitter_simple_random[[i + hitter_stat_num*(j - 1)]] <- plm(formula, data = hitter_data,
                                                  model = "random",
                                                  index = c("id", "Anio_ref"))
        
    hitter_results_simple_random[[j]][[i]] <- coeftest(hitter_simple_random[[i + hitter_stat_num*(j - 1)]],
                                                        vcov = vcovHC(hitter_simple_random[[i + hitter_stat_num*(j - 1)]],
                                                                      type = "HC1",
                                                                      cluster = "group"))
  }
  
  # Print the third block of results
  stargazer(hitter_results_simple_random[[j]],
          no.space = TRUE,
          type = "latex",
          title = "Bateadores: Efectos Aleatorios",
          covariate.labels = hitter_stats[[j]])
}
```

### Starting pitcher

```{r starting_stimation_random, echo=FALSE, eval=TRUE}
# Create a model to store the results
fielder_simple_random <- list()

# To store the results
fielder_results_simple_random_1 <- list()
fielder_results_simple_random_2 <- list()
fielder_results_simple_random_3 <- list()
fielder_results_simple_random_4 <- list()
fielder_results_simple_random_5 <- list()
fielder_results_simple_random <- list(result_1 = fielder_results_simple_random_1,
                                       result_2 = fielder_results_simple_random_2,
                                       result_3 = fielder_results_simple_random_3,
                                       result_4 = fielder_results_simple_random_4,
                                       result_5 = fielder_results_simple_random_5)

# Loop over the variables in var_hitter_list
for (j in 1:fielder_rep){
  
  for (i in 1:fielder_stat_num){
    # Run linear regression with grouped errors by country and robust errors
    base_vars_h  <- paste(vars_ms, stat_fielder_t[[i + fielder_stat_num*(j - 1)]],
                        sep = '+')
    formula <- paste(base_vars_h,
                     stat_fielder_t_1[[i + fielder_stat_num*(j - 1)]],
                     sep = " + ")
    
    fielder_simple_random[[i + hitter_stat_num*(j - 1)]] <- plm(formula, data = starting_data,
                                                  model = "random",
                                                  index = c("id", "Anio_ref"))
        
    fielder_results_simple_random[[j]][[i]] <- coeftest(fielder_simple_random[[i + fielder_stat_num*(j - 1)]],
                                                         vcov = vcovHC(fielder_simple_random[[i + fielder_stat_num*(j - 1)]],
                                                                       type = "HC1",
                                                                       cluster = "group"))
  }
  
  # Print the third block of results
  stargazer(fielder_results_simple_random[[j]],
          no.space = TRUE,
          type = "latex",
          title = "Lanzadores Iniciales: Efectos Aleatorios",
          covariate.labels = fielder_stats[[j]])
}
```